import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
import clsx from "clsx";
import Link from "next/link";
import { Nav } from "./nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="bg-[conic-gradient(at_bottom_right,_var(--tw-gradient-stops))] from-yellow-800 via-orange-400 to-indigo-600"
    >
      <body className={clsx(GeistMono.className, "text-stone-200")}>
        <div className="w-screen h-screen fixed grain" />
        <div className="relative z-20 flex min-h-screen flex-col p-24 gap-8">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
