import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
import clsx from "clsx";
import { Nav } from "./nav";
import topWrap from "../../public/top-wrap.png";
import bottomWrap from "../../public/bottom-wrap.png";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(GeistMono.className, "relative text-stone-100 bg-stone-950 max-w-7xl mx-auto")}>
        <div className="grain fixed h-screen w-screen" />
        <div className="relative z-20 flex min-h-screen flex-col gap-8 p-24">
        <div className="flex h-12 w-full items-center">
          🚧 This site is a work in progress! 🚧
        </div>
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
